pypyr/pypyr

ops/deploy.sh
Simple PR. This is to promote to minor release rather than patch.
=> parameterize ops deploy to use bumplevel switch

README.rst, pypyr/context/commas.py, pypyr/context/json.py, pypyr/context/jsonfile.py, pypyr/context/keyvaluepairs.py, pypyr/moduleloader.py, pypyr/pipelinerunner.py, pypyr/steps/contextset.py, pypyr/steps/echo.py, pypyr/steps/py.py, pypyr/steps/pypyrversion.py, pypyr/steps/safeshell.py, pypyr/steps/shell.py, pypyr/stepsrunner.py, tests/unit/pypyr/steps/contextset_test.py, tests/unit/pypyr/steps/py_test.py, tests/unit/pypyr/steps/pypyrversion_test.py
- From now on a pipeline context is always a dictionary. - Simple is better than complex
- a pipeline step's  `def run_step(context)` used to require a return type `return context`. This is a hang-over from the early days of pypyr where I was still thinking that a context could by anything - a plain old string, or a dictionary, or a stream (file-like objects in pythonese), or a whatever. 
- So if the `run_step(context)` was to be an immutable type (e.g a string), then any alterations to the context inside the run_step wouldn't have made it back out of the func unless _explicitly_ returned as a new obj `return mymanipulatedblah`. Hence the 1st design with the explicit return required.
- Given the heavy preponderance of mutable dictionary usage for the context for pretty much everything, …
=> Breaking Change: step signature change

README.rst, pypyr/context/keyvaluepairs.py, pypyr/format/__init__.py, pypyr/format/string.py, pypyr/steps/safeshell.py, pypyr/steps/shell.py, shippable.yaml, tests/unit/pypyr/format/string_test.py, tests/unit/pypyr/steps/safeshell_test.py, tests/unit/pypyr/steps/shell_test.py
- Add string formatter that does string interpolation. For "blah {key} blah", yield "blah blah blah" if context key=blah.
- Shell and Safeshell uses string interpolator.
- Readme updates to describe new functionality.
=> String Interpolation

README.rst, pypyr/context.py, pypyr/version.py, setup.cfg, tests/unit/pypyr/context_test.py
-  `asserts_keys_have_values(self, keys, caller)` is now `assert_keys_have_values(self, caller, *keys)`
- add pypi version badge to readme
=> Assert validator signature changes

README.rst, pypyr/cli.py, pypyr/pipelines/donothing.yaml, pypyr/pipelines/echo.yaml, pypyr/pipelines/magritte.yaml, pypyr/pipelines/pypyrversion.yaml, pypyr/version.py, setup.cfg, tests/unit/pypyr/__main__test.py, tests/unit/pypyr/cli_test.py
- the cli now takes --name as default. instead of `pypyr --name mypipe` it's `pypyr mypipe`
- log level defaults to INFO
- signal interrupt handled (ctrl + c)
- stderr output red
=> Breaking change: What's my --name?

README.rst, pypyr/cli.py, pypyr/steps/env.py, pypyr/version.py, setup.cfg, tests/unit/pypyr/cli_test.py, tests/unit/pypyr/steps/env_test.py
- envSet from pypyr.steps.env uses format strings. Breaking change - previously these took values directly from context based on key.
- add TRACE level logging for full traceback
=> EnvSet uses formatstrings and TRACE

README.rst, pypyr/context.py, pypyr/errors.py, pypyr/steps/contextclear.py, pypyr/steps/contextclearall.py, pypyr/steps/echo.py, pypyr/steps/py.py, pypyr/steps/tar.py, pypyr/stepsrunner.py, tests/unit/pypyr/context_test.py, tests/unit/pypyr/errors_test.py, tests/unit/pypyr/pipelinerunner_test.py, tests/unit/pypyr/steps/contextclear_test.py, tests/unit/pypyr/steps/contextclearall_test.py, tests/unit/pypyr/steps/contextset_test.py, tests/unit/pypyr/steps/echo_test.py, tests/unit/pypyr/steps/py_test.py, tests/unit/pypyr/steps/safeshell_test.py, tests/unit/pypyr/steps/shell_test.py, tests/unit/pypyr/steps/tar_test.py, tests/unit/pypyr/stepsrunner_test.py
- KeyNotInContextError and KeyInContextHasNoValueError added. Refactor throughout to use new errs rather than KeyError. 
- NB: henceforth, Context throws KeyNotInContextError, not KeyError, on __ missing __
- echoMe refactor to deal more sensibly with non-str types
- py.step had unreachable code, removed.
- new steps:
- tar
- contextclear
- contextclearall
- stepsrunner had unreachable code (steps can't re-assign context to None due to python call-by-obj param passing)
- bug fixes for format strings missing f""
- bug fix: complex steps exploded if didn't have the optional "in" context specified.
- 100% test coverage as of now
=> Steps: tar, contextclear, contextclearall. Errs: KeyNotInContext, KeyInContextHasNoValue

pypyr/context.py, pypyr/version.py, setup.cfg, tests/unit/pypyr/context_test.py
- Add recursive string interpolation so can format iterable and nested iterable types
- get_formatted will now, instead of raising typerror on non-str, use the recursive function to parse types other than str
- version bump for patch release
=> recursive string interpolation for iterable types

pypyr/context.py, pypyr/utils/poll.py, pypyr/version.py, setup.cfg, tests/unit/pypyr/context_test.py, tests/unit/pypyr/utils/poll_test.py
- add pypyr utils _wait_until_true_. This allows you to decorate any given function with `@wait_until_true(interval, max_attempts)` and it will execute that function on the specified intervals until max attempts reached, until the function returns true.
- add context get_formatted_as_type, to format string values AND return as a certain type that's not necessarily a string.
=> wait_until_true decorator

pypyr/context.py, pypyr/version.py, setup.cfg, tests/unit/pypyr/context_test.py
- get_formatted_as_type previously would return True for all str -> bool conversions. Now 'True' will return `True`, and all other strings return `False` when casting to bool.
- version bump
=> get_formatted_as_type does bools

pypyr/pipelinerunner.py, pypyr/version.py, setup.cfg, tests/unit/pypyr/pipelinerunner_test.py
- If pypyr context can't create, create an empty pypyr Context to allow failure handler steps access to the pypyr Context even if empty - steps reasonably can expect a Context-like type input
- version bump
=> Failure handler initializes empty pypyr Context

pypyr/steps/tar.py, pypyr/version.py, setup.cfg, tests/unit/pypyr/steps/tar_test.py
- tar archive would take an inpath like */path/to/mydir* and tar the entire path as */path/to/mydir*, rather than just add *mydir* to the tar. As of now, only the destination dir, and not its parents, will end up in the tar.
- version bump
=> tar archive only the last dir

README.rst, pypyr/steps/assert.py, pypyr/version.py, setup.cfg, tests/unit/pypyr/steps/assert_test.py
- add pypyr.steps.assert. Provide debug .assert style functionality in a pypyr step
- README updates 
- assert
- nested formatting expressions
- thank yous
- bump version
=> assert step

README.rst, pypyr/steps/assert.py, pypyr/steps/contextsetf.py, pypyr/version.py, setup.cfg, tests/unit/pypyr/steps/assert_test.py, tests/unit/pypyr/steps/contextsetf_test.py
- contextsetf step. Set context keys from formatting expressions with {substitutions}.
- assert step - friendlier error messages include type information
- README updates for new functionality
- bump
=> contextsetf, and nicer assert errors

README.rst, ops/shippable-pypi-release.sh, pypyr/version.py, setup.cfg
- let twine choose pypi url rather than specify it
- minor README updates for pype recursion
=> twine deployment url change

.gitignore, README.rst, pypyr/parser/yamlfile.py, pypyr/pipelinerunner.py, pypyr/steps/assert.py, pypyr/steps/fetchyaml.py, pypyr/steps/fileformatyaml.py, pypyr/version.py, setup.cfg, setup.py, tests/unit/pypyr/pipelinerunner_test.py, tests/unit/pypyr/steps/fileformatyaml_test.py
- upgrade version for new pypi release
- update ruamel.yaml to >0.15. This is a major, interface breaking change on the part of ruamel. pypyr consumers are not affected, however.
- add fileformatyaml.yaml example
- .pytest_cache to gitignore
- minor formatting change on new linting rules for = on a single line
=> ruamel.yaml upgrade to >0.15

README.rst, pypyr/context.py, pypyr/stepsrunner.py, pypyr/version.py, setup.cfg, tests/unit/pypyr/context_test.py, tests/unit/pypyr/steps/assert_test.py, tests/unit/pypyr/stepsrunner_test.py
- Add step decorators for run, skip and swallow
- You can now specify on the fly whether a step should run, be skipped or if any errors should be ignored.
- string to bool type conversions now cater for TRUE/true/True/1/1.0 casting to bool True
- fix bug on casting where return value is not actually cast to specified return_type
- Minor version release
=> Step Decorators: run, skip, swallow

README.rst, pypyr/cli.py, pypyr/parser/commas.py, pypyr/parser/json.py, pypyr/parser/jsonfile.py, pypyr/parser/keyvaluepairs.py, pypyr/parser/list.py, pypyr/parser/string.py, pypyr/parser/yamlfile.py, pypyr/pipelines/echo.yaml, pypyr/steps/echo.py, pypyr/steps/py.py, pypyr/steps/pype.py, pypyr/steps/safeshell.py, pypyr/steps/shell.py, pypyr/version.py, setup.cfg, tests/unit/pypyr/cli_test.py, tests/unit/pypyr/parser/list_test.py, tests/unit/pypyr/parser/string_test.py, tests/unit/pypyr/steps/echo_test.py
- `pypyr pipelinename --context blah` is now `pypyr pipelinename blah`
- pypyr.parser.string simple string context parser
- rewire builtin echo pipeline to use pypyr.parser.string parser
- help and readme updates for --context removal
=> remove --context arg, make positional

pypyr/version.py, setup.cfg, shippable.yaml
- no functional change. fix shippable deploy only to deploy to pypi on 3.7 build, rather than both 3.6 and 3.7
- version bump to 1.1.1
=> Shippable matrix only deploy on 3.7

pypyr/context.py, tox.ini
amend flake8 err where both w503 and w504 (linebreaks before operators). Breakage due to flake8 oct update.
http://flake8.pycqa.org/en/latest/release-notes/3.6.0.html
Adding a default select switch to the flake8 select seems to do the job.
=> flake8 october update breakages

pypyr/pipelinerunner.py, tests/unit/pypyr/pipelinerunner_test.py, tests/unit/pypyr/steps/safeshell_test.py
Split run_pipeline function on two: 
- load_and_run_pipeline
- run_pipeline
The main reason is to add capability to call pipeline context directly. See example of use case inside issue #80
=> Add new function to load and run pipeline

README.rst, pypyr/context.py, pypyr/dsl.py, pypyr/moduleloader.py, pypyr/pipelinerunner.py, pypyr/utils/expressions.py, pypyr/utils/types.py, pypyr/yaml.py, tests/unit/pypyr/context_test.py, tests/unit/pypyr/dsl_test.py, tests/unit/pypyr/utils/expressions_test.py, tests/unit/pypyr/utils/types_test.py, tests/unit/pypyr/yaml_test.py
- pypyr dsl expanded to accept custom tag parsers for literal parsing. This simplifies and hardens how sic strings work - instead of relying on string-parsing on "[sic]" and the tricky use of quotes and double-quotes, now a structural yam tag identifies sic string, making it a whole lot simpler to write sic strings with special characters in them without escape sequences or having to deal with `"'\'{blah}\''"` style eye-bleeding messes.
- this is a relatively big refactor under the covers, and it's a breaking change to how sic strings. Justified because the improvement in ease of use is massive.
- introduce Py Strings. These allow dynamic eval of python expressions anywhere you can use a string formatting expression in a pipeline.
- minor enhancement to initialise whileCounter before loop …
=> py strings ref #89. big refactor to use special tag directives.

pypyr/version.py, setup.cfg, tox.ini
- pypyr v2.0.0 release!
- BREAKING CHANGES:
- [sic] strings are now a lot better. Instead of relying on string-parsing on "[sic]" and the tricky use of quotes and double-quotes, now a structural yam tag identifies sic string, making it a whole lot simpler to write sic strings with special characters in them without escape sequences or having to deal with "'\'{blah}\''" style eye-bleeding messes. This does mean, however, that old style "[sic]" strings won't work anymore.
- new features:
- Py Strings. These allow dynamic eval of python expressions anywhere you can use a string formatting expression in a pipeline. Thank you to  @Reskov for the idea, and working through the scenarios and options!
- Write yaml or json to disk using `pypyr.steps.filewriteyaml` and `pypyr.steps.filewritejson`
- …
=> pypyr v2.0.0 - [sic] strings breaking change

README.rst, pypyr/steps/cmd.py, pypyr/steps/dsl/cmd.py, pypyr/steps/safeshell.py, tests/unit/pypyr/steps/cmd_step_test.py, tests/unit/pypyr/steps/dsl/cmd_test.py, tests/unit/pypyr/steps/safeshell_test.py
* Shell/Safeshell can save stdout and stderr. ref #71 
* Add _pypyr.steps.cmd_ to replace .safeshell. Safeshell will still work as an alias. cmd is less confusing  vs _pypyr.steps.shell_
=> cmd out save to context. closes #71

pypyr/parser/commas.py, pypyr/parser/json.py, pypyr/parser/keyvaluepairs.py, pypyr/parser/list.py, pypyr/parser/string.py, tests/unit/pypyr/parser/commas_test.py, tests/unit/pypyr/parser/json_test.py, tests/unit/pypyr/parser/keyvaluepairs_test.py, tests/unit/pypyr/parser/list_test.py, tests/unit/pypyr/parser/string_test.py
- make built-in context parsers input arguments optional to allow pipelines with context_parsers to be executed with or without an extra argument from the cmd line. ref #69
=> built-in context parsers optional args. closes #69

pypyr/dsl.py, pypyr/errors.py, tests/unit/pypyr/context_test.py, tests/unit/pypyr/utils/expressions_test.py
`Context` must raise exception inherited from base `KeyError` class, when some key is not found at `Context` object.
The `test_expr_derived_dicts_fail` is not actual anymore.
=> Context must save behavior of dict on missing key.

README.rst, pypyr/cli.py, pypyr/pipelines/echo.yaml, pypyr/pipelines/magritte.yaml, pypyr/steps/envget.py, pypyr/version.py, setup.cfg, tests/unit/pypyr/cli_test.py, tests/unit/pypyr/steps/envget_test.py
- add new step _pypyr.steps.getenv_ Whereas _pypyr.steps.env_ raises an error if you are getting an environment variable that doesn't exist, the new _envget_ allows you to specify a default value to use instead. ref #111 
- some documentation updates to demonstrate how to use py strings for ternary assignments
- built-in pypes use _comment_ rather than _description_ where output is not meant for operator consumption ref #109 
- alias the `--loglevel` switch with `--log`, so you can now do `pypyr mypipe --log 10` think of the savings just on keyboard wear and tear!
- new minor version release
=> pypyr.steps.getenv

README.rst, pypyr/steps/envget.py, pypyr/steps/fetchjson.py, pypyr/steps/fetchyaml.py, pypyr/steps/pathcheck.py, pypyr/version.py, setup.cfg, tests/integration/pypyr/steps/pathcheck_int_test.py, tests/unit/pypyr/steps/envget_test.py, tests/unit/pypyr/steps/fetchjson_test.py, tests/unit/pypyr/steps/fetchyaml_test.py, tests/unit/pypyr/steps/pathcheck_test.py
- The new _pypyr.steps.pathcheck_ step allows you see if a path exists on the filesystem. It supports literal paths and glob expansions. It writes handy values into `pathCheckOut`with bool for existence and count of files found for the given path. #114 
- deprecate old style multi context inputs for fetchjson and fetchyaml, #118. this is not just arbitrary: reason is when step is used multiple times in same pipeline, it becomes easy to have left-over values from previous step run left in context that then cause surprising behaviour with the downstream step. the old style is still supported by virtue of pypyr creating the new style inputs under the hood if it finds the old style arguments - but you can expect this to go away by the next major release.
- add info output logging to envget
=> pypyr.steps.pathcheck & deprecate multi-input fetches

README.rst, pypyr/steps/dsl/cmd.py, pypyr/version.py, setup.cfg, tests/unit/pypyr/steps/cmd_step_test.py, tests/unit/pypyr/steps/dsl/cmd_test.py
- use the new `cwd` input on _pypyr.steps.cmd_ and _pypyr.steps.shell_ to set the current working directory for the program/shell that you want to execute. Supports relative paths. 
- bump version to 2.5.0
=> pypyr.steps.cmd and pypyr.steps.shell can set working directory

README.rst, pypyr/steps/now.py, pypyr/steps/nowutc.py, pypyr/version.py, setup.cfg, setup.py, tests/unit/pypyr/steps/now_test.py, tests/unit/pypyr/steps/nowutc_test.py
- get the current datetime stamp into the pypyr context as a formattable string, where you can specify your own datetime formats using the standard python date time replacement tokens like '%Y-%m-%d' for YYYY-MM-DD.
- adds python-dateutil as setup dependency
=> pypyr.steps.now and nowutc closes ref #131

README.rst, pypyr/dsl.py, pypyr/errors.py, pypyr/version.py, setup.cfg, tests/unit/pypyr/dsl_test.py, tests/unit/pypyr/errors_test.py, tests/unit/pypyr/stepsrunner_test.py
- new Retry decorator allows steps to retry automatically when step encounters an error. ref #130 
- fix run_step AttributeError might have caught or hidden AttributeErrors in the step code itself, rather than just when the step module didn't contain a run_step function. ref #129
- while loop checks `stop` condition only at end of each iteration. previously if a stop condition evaluated True even before the loop started the loop wouldn't run at all. now the loop will run once. If you don't want the step to run, use the `skip: True` decorator instead.
- documentation updates for all the above
- version bump for new release.
=> RetryDecorator and while loop stop condition until style

pypyr/moduleloader.py, pypyr/version.py, setup.cfg, tests/arbpack/arbinvalidimportmod.py, tests/unit/pypyr/moduleloader_test.py
* When importing a step that does exist (`mystep.blah`), a failing `import mymodule.blah` inside `mystep.blah` would give a misleading error and hide the actual source of the problem. Fixes #166
* version bump for release
=> friendlier error message on import errors

pypyr/context.py, pypyr/version.py, setup.cfg, tests/unit/pypyr/context_test.py
- Allow non-string keys on `context.get_formatted_iterable` and context merge (including `pypyr.steps.contextmerge`). Resolves #179.
- Version bump for patch release
=> Allow formatting & merging on non-string keys on Mapping objects

README.rst, pypyr/version.py, setup.cfg, setup.py
- Update documentation and pypi setup with new repo name.
- bump version to publish.
=> Repo rename from pypyr-cli to pypyr

pypyr/log/logger.py, pypyr/moduleloader.py, pypyr/pipelinerunner.py, pypyr/pypeloaders/fileloader.py, pypyr/steps/echo.py, pypyr/steps/pype.py, pypyr/version.py, setup.cfg, tests/arbpack/naivefileloader.py, tests/integration/pypyr/pipelinerunner_int_test.py, tests/integration/pypyr/pype/pype_int_test.py, tests/pipelines/api/main-all.yaml, tests/pipelines/pype/childpipeargs.yaml, tests/pipelines/pype/childpipeargs_noparent.yaml, tests/pipelines/pype/pipeargs.yaml, tests/pipelines/pype/pipeerr.yaml, tests/pipelines/pype/pipeerr_child.yaml, tests/unit/pypyr/cli_test.py, tests/unit/pypyr/log/logger_test.py, tests/unit/pypyr/moduleloader_test.py, tests/unit/pypyr/pipelinerunner_test.py, tests/unit/pypyr/steps/pype_test.py
- Streamline main entrypoint API. close #201.
- `main()` allows consumer to set pype loader, rather than having to drop further down into api to load_and_run_pipeline()
- new `main_with_context()` to input dict to initialise context, and bypass context_parser entirely. Also returns the `Context` object after pipeline run completes.
- make all non-essential args optional to allow minimal calls to main entrypoint without having to add `optional=None` style inputs.
- This is fully backwards compatible.
- `pypyr.steps.pype`
- defaults `useParentContext` to `False` is `pipeArgs` specified.
- `pipeArgs` shlex-es input string
- set `pipeline_name` on child pipeline rather than use parent pipeline name
- `working_dir` uses `Path` object rather than string
- `pypyr.steps.echo` remove redundant …
=> streamlined api entry-points

pypyr/cache/namespacecache.py, pypyr/context.py, pypyr/dsl.py, pypyr/moduleloader.py, pypyr/steps/contextclearall.py, pypyr/steps/pyimport.py, pypyr/utils/expressions.py, tests/arbpack/arbmod2.py, tests/arbpack/arbmod3.py, tests/arbpack/arbmod4_avoid.py, tests/arbpack/arbmultiattr.py, tests/integration/pypyr/pype/pype_int_test.py, tests/pipelines/pype/pyimport/child-new-context.yaml, tests/pipelines/pype/pyimport/child-parent-context.yaml, tests/pipelines/pype/pyimport/parent.yaml, tests/unit/pypyr/cache/namespacecache_test.py, tests/unit/pypyr/context_test.py, tests/unit/pypyr/dsl_test.py, tests/unit/pypyr/moduleloader_test.py, tests/unit/pypyr/steps/contextclearall_test.py, tests/unit/pypyr/steps/pyimport_test.py, tests/unit/pypyr/utils/expressions_test.py, tests/unit/pypyr/yaml_test.py
- new step `pypyr.steps.pyimport` to import references to the py-string namespace.
- This includes an underlying api signature change to `pypyr.utils.expressions.eval_string()`, but this is sufficiently far down the call-chain that it shouldn’t affect any normal pipeline operator or api consumer.
- `pypyr.steps.contextclearall` wipes pyimport imported references in addition to the key/values inside context.
=> pypyr.steps.pyimport.

pypyr/dsl.py, tests/unit/pypyr/dsl_test.py
=> Fix retry decorator max substitution

ops/build.yaml, pypyr/version.py, setup.cfg
- fix ops/build to use new `py` style syntax for `pypyr.steps.py` 
- version bump for release
Release contains:
- New step `pypyr.steps.pyimport` to import references to the py-string namespace.
- This includes an underlying api signature change by removal of `pypyr.utils.expressions.eval_string()`, but this is sufficiently far down the call-chain that it shouldn’t affect any normal pipeline operator or api consumer.
- `pypyr.steps.contextclearall` wipes `pyimport` imported references in addition to the key/values inside context.
- Simplify `pypyr.steps.py` syntax by allowing a new `py` (rather than `pycode`) input. This allows pipeline authors to use context key names directly as variables, rather than have to specify them as keys in context (`my_var` vs `context[‘my_var’]`).
- see #204 …
=> release 4.4.0

pypyr/parser/dict.py, pypyr/parser/list.py, pypyr/parser/string.py, pypyr/version.py, setup.cfg, tests/unit/pypyr/parser/dict_test.py, tests/unit/pypyr/parser/list_test.py, tests/unit/pypyr/parser/string_test.py
- context parsers that create an entry in context currently initialise to `None`. this is annoying downstream because you constantly have to deal with the None exception case - e.g you can't just directly jump into a `for` loop. closes #214.
- version bump for release
=> context parsers initialize empty rather than None. closes #214.

pypyr/cache/backoffcache.py, pypyr/dsl.py, pypyr/retries.py, pypyr/utils/poll.py, tests/arbpack/arbcallables.py, tests/integration/pypyr/retries/retry_int_test.py, tests/pipelines/retries/retry-anchors.yaml, tests/unit/pypyr/cache/backoffcache_test.py, tests/unit/pypyr/dsl_test.py, tests/unit/pypyr/retries_test.py, tests/unit/pypyr/utils/poll_test.py
- Add retry backoff strategies. #216.
- the `while_until_true` looper now also accepts a `callable` to calculate sleep interval for the `sleep` interval. You can still pass a `float`, so this is fully backwards compatible.
- the retry poller confused coverage with evaluating the `while bool_here` dynamically, necessitating nopragma. The loops in question all `break` explicitly for all possible exit conditions that break out of loop, so the extra while eval condition not actually necessary. Thus, remove & simplify. No functional change.
=> retry backoff

conftest.py, pypyr/__init__.py, pypyr/cache/cache.py, pypyr/log/logger.py, pypyr/moduleloader.py, pypyr/pipelinerunner.py, pypyr/version.py, setup.cfg, tests/unit/pypyr/__init__test.py, tests/unit/pypyr/log/logger_test.py, tests/unit/pypyr/moduleloader_test.py, tests/unit/pypyr/pipelinerunner_test.py
- prevent duplicates in `sys.path` (#218) on main* api entry points. thread-safe existence check on `sys.path` list.
- prevent redundant multiple addition of notify log-level on main* api entry. Move initialization code to package `__init__`.
- version bump for minor new release
=> cleaner api initialization

pypyr/steps/add.py, pypyr/steps/append.py, pypyr/utils/asserts.py, tests/unit/pypyr/steps/add_test.py, tests/unit/pypyr/steps/append_test.py, tests/unit/pypyr/utils/asserts_test.py
Close #121.
New steps for handling lists & sets:
- pypyr.steps.append
- append or extend items to a list
- pypyr.steps.add
- add or update a set
- New validation/assert helper for truthy checks on context input.
=> pypyr.steps.append & pypyr.steps.add

.github/workflows/lint-test-build.yaml, README.md, pypyr/pipelines/echo.yaml, pypyr/steps/set.py, pypyr/version.py, setup.cfg, setup.py, tests/unit/pypyr/steps/set_test.py
- add new step `pypyr.steps.set` as an alternative for `pypyr.steps.contextsetf`
- update min required Python to 3.7
- update pypi trove classifiers, removing 3.6 and adding 3.10
- simplify built-in `echo` pipeline - no functional change
=> shorter alias `set` for `contextsetf`. py 3.10.

pypyr/steps/fileread.py, pypyr/utils/asserts.py, tests/unit/pypyr/steps/fileread_test.py, tests/unit/pypyr/utils/asserts_test.py
- add `pypyr.steps.fileread` to read files in text or binary mode into context.
- add `assert_keys_are_truthy` validator - this allows steps to use only 1 line to check for multiple child-keys on a step input.
=> pypyr.steps.fileread

pypyr/steps/fileread.py, pypyr/steps/filewrite.py, pypyr/steps/filewritejson.py, pypyr/steps/filewriteyaml.py, tests/unit/pypyr/steps/filewrite_test.py, tests/unit/pypyr/steps/filewritejson_test.py, tests/unit/pypyr/steps/filewriteyaml_test.py
- add `pypyr.steps.filewrite` to write or append file in text or binary modes
- amend `filewriteyaml` to use `Path` rather than `os` - no functional change
- `pypyr.steps.fileread` binary check is truthy, rather than `is True`
=> pypyr.steps.filewrite

pypyr/cache/loadercache.py, tests/unit/pypyr/cache/loadercache_test.py
Friendlier err msg when top-level yaml is not a Mapping (i.e it's a Sequence or Scalar.)
This check prevents malformed pipeline from even making it into the pipeline cache.
Closes #249
=> friendly err on malformed pipeline.

.github/workflows/lint-test-build.yaml, .github/workflows/publish.yaml, .github/workflows/tag-release.yaml, ops/build.yaml, pypyr/steps/python.py, pypyr/version.py, setup.cfg, tests/unit/pypyr/steps/fileformattoml_test.py, tests/unit/pypyr/steps/python_test.py
- add `pypyr.steps.python` steps to write value of current Python executable into context. See #265
- amend ops/build to use this new step and `{python}` in subsequent cmds running Python as a subprocess from pypyr
- now that upstream `pyfakefs` released patch, amend unit tests for passing encoding to a binary mode where an error is expected.
- minor release version bump
=> pypyr.steps.python & version bump 5.2.0

ops/tag.yaml, pypyr/aio/__init__.py, pypyr/aio/subproc.py, pypyr/config.py, pypyr/errors.py, pypyr/steps/cmds.py, pypyr/steps/dsl/cmdasync.py, pypyr/steps/shells.py, pypyr/subproc.py, tests/integration/pypyr/steps/cmds_int_test.py, tests/unit/pypyr/aio/aio_subproc_test.py, tests/unit/pypyr/config_test.py, tests/unit/pypyr/errors_test.py, tests/unit/pypyr/steps/cmd_step_test.py, tests/unit/pypyr/steps/cmds_test.py, tests/unit/pypyr/steps/dsl/cmd_test.py, tests/unit/pypyr/steps/dsl/cmdasync_test.py, tests/unit/pypyr/steps/shell_test.py, tests/unit/pypyr/steps/shells_test.py, tests/unit/pypyr/subproc_test.py
- Run commands/shells concurrently as a subprocess
- Implemented with asyncio
- New `pypyr.steps.cmds` and `pypyr.steps.shells` steps are asynchronous analogues of existing `pypyr.steps.cmd` and `pypyr.steps.shell` steps
- Async cmd encoding configurable with new `config.default_cmd_encoding`
- closes #273  
- `cmdOut` for `pypyr.steps.cmd` & `pypyr.steps.shell` gets dotted attribute access.
- instead of `cmdOut[returncode]` access value like this: `cmdOut.returncode`
- backwards compatible - the old-style dict-like accessors will still work.
- closes #272
=> async cmds + shells

.gitignore, pypyr/aio/subproc.py, pypyr/config.py, pypyr/subproc.py, pypyr/version.py, setup.cfg, tests/integration/pypyr/steps/cmds_int_test.py, tests/unit/pypyr/aio/aio_subproc_test.py, tests/unit/pypyr/config_test.py, tests/unit/pypyr/steps/dsl/cmdasync_test.py
- `SubprocessResult` saves shlexed args split, rather than original input command string.
- This assists pipeline operator debugging/troubleshooting, to see easily if there were any surprises with whitespace/special char escaping on the cmd input string.
- No backwards compatibility issue, since `SubprocessResult` code as is has not released yet.
- Apply `config.DEFAULT_CMD_ENCODING` to serial cmd/shell too. Previously it only applied to async cmds/shells.
- version bump for minor release. This will release the new async cmds/shells functionality.
Housekeeping:
- exclude mypy cache from gitignore.
=> release 5.5 & default_cmd_encoding for serial

.github/workflows/lint-test-build.yaml, .github/workflows/publish.yaml, .github/workflows/tag-release.yaml
- upgrade GitHub actions checkout from v2 to v3 for all actions.
=> gh action checkout v3

pypyr/__init__.py, pypyr/parser/argskwargs.py, pypyr/parser/dict.py, pypyr/parser/keyvaluepairs.py, setup.cfg, tests/unit/pypyr/parser/argskwargs_test.py, tests/unit/pypyr/parser/dict_test.py, tests/unit/pypyr/parser/keyvaluepairs_test.py
- new `argskwargs` parser for combining list of args with keyword args. closes #284.
- amend `keyvaluepairs` and `dict` parsers to allow unescaped = in values - only the 1st `=` is now taken to identify the key, the subsequent string becomes the value.
- similarly, inputs without `=` will not raise a ValueError anymore, instead it will parse to `key: ''` - i.e the arg input value as key with an empty string as a value.
- minor release bump
=> argskwargs parser & partitioning on = for kvp

pypyr/steps/dsl/fileinoutrewriter.py, tests/unit/pypyr/steps/dsl/fileinoutrewriter_test.py
- `get_formatted` runs a redundant second time on filereplace inputs. Mostly this will just result in burning unnecessary CPU, but it will also cause `ff` flat format directives to get lost.
- closes #303.
=> pypyr.steps.filereplace get_formatted X2

.github/workflows/lint-test-build.yaml, pyproject.toml, pypyr/toml.py, tests/unit/pypyr/steps/fetchtoml_test.py
- Add python 3.11 trove classifiers.
- Only install tomli when python_version < 3.11.
- Conditional import of tomli.
- Github action add 3.11 runner.
=> py 3.11 & conditional tomli dep

.github/workflows/lint-test-build.yaml, .github/workflows/publish.yaml, pypyr/cache/admin.py, pypyr/cache/filecache.py, pypyr/loaders/file.py, tests/unit/pypyr/cache/admin_test.py, tests/unit/pypyr/loaders/file_test.py, tox.ini
- upgrade to tox 4.
- breaking change on passenv going comma rather than space delimited.
- codecov add token to GitHub action to avoid sporadic errors on codecov coverage upload
- Add clear all function to wipe all pypyr caches. Closes #316
=> clear all cache, codecov token, tox 4 

pypyr/cache/backoffcache.py, pypyr/cache/cache.py, pypyr/config.py, tests/unit/pypyr/cache/backoffcache_test.py, tests/unit/pypyr/cache/cache_test.py, tests/unit/pypyr/config_test.py
Add no_cache config flag, defaulting to False.
When no_cache=True, pypyr will bypass the internal caches entirely. pypyr will NOT retrieve anything from cache nor save anything to cache while no_cache=True.
Setting this flag has no effect on items currently in cache, but any get() operation on a cache won't even look at these existing items while the no_cache flag is True, nor add anything new to the cache.
Add some special handling for built-in retry back-offs. These use the backoff cache to map the built-ins' simple short names (e.g `fixed`) to the fully qualified (`pypyr.retries.fixed`). In the case where the `no_cache` bypass hits `load_backoff_callable` directly, pull short-names directly from the `builtin_backoffs`. This effectively ignores the underlying cache, and the super's …
=> no cache mode

pypyr/__init__.py, setup.cfg
Release for  no cache & clear all cache.
- convenience function to clear all caches in one. Closes #316.
```python
import pypyr.cache.admin as cache_admin
cache_admin.clear_all()
```
- disable caching entirely with new `no_cache` mode. Closes #317 
```python
from pypyr.config import config
from pypyr import pipelinerunner
config.no_cache = True
context = pipelinerunner.run(pipeline_name='my-pipe')
```
=> Bump version: 5.7.1 → 5.8.0

pypyr/dsl.py
ruamel has had a breaking change where `construct_undefined` stopped working. `construct_unknown` seems to be the better method now.
Closes #327
=> fix jsonify tag ruamel

pypyr/loaders/string.py, tests/integration/pypyr/loaders/string_loader_test.py, tests/unit/pypyr/loaders/string__test.py
Adds the ability to load pipelines from a string instead of a file path. Useful for testing or for invoking the runner using a pipeline that doesn't come from the file system.
=> String Loader

pypyr/__init__.py, setup.cfg
-  Adds a new string loader for pipelines - you can now load pipelines directly from a string.
-  Fixes issue with `!jsonify` custom tags failing to load with error "ruamel.yaml.constructor.ConstructorError: could not determine a constructor for the tag '!jsonify'" - this was due to a regression in the ruamel dependency
=> Bump version: 5.8.0 → 5.9.0

pyproject.toml, pypyr/__init__.py, setup.cfg
To make sure installation get the latest ruamel dependency.
The code now depends on the newer 'RoundTripConstructor' object to have attribute 'construct_unknown'
Increase patch version to release this version dependency to pypi.
=> ruamel version pin
