README.rst, pypyr/context/json.py, pypyr/context/jsonfile.py, pypyr/steps/contextset.py, pypyr/validate/asserts.py, setup.py, tests/testfiles/test.json, tests/unit/pypyr/context/jsonfile_test.py, tests/unit/pypyr/steps/contextset_test.py, tests/unit/pypyr/steps/safeshell_test.py, tests/unit/pypyr/steps/shell_test.py, tests/unit/pypyr/validate/assert_test.py
- add jsonfile context_parser
- add contextset step
- add core validators for context dict validation
- add `pypyr` entrypoint so can use pypyr rather than pypyrcli namespace when consuming lib
=> pypyr namespace, jsonfile parser, contextSet step, context validator

README.rst, pypyr/validate/__init__.py
=> add init.py to validate sub to fix wheel

pypyr/validate/asserts.py, tests/unit/pypyr/validate/assert_test.py
=> add keys in context list validator

pypyr/errors.py, pypyr/version.py, setup.cfg, tests/unit/pypyr/errors_test.py
- Add custom errors definitions to pypyr
- Not particularly in use in the core (yet), but the plug-ins are using them
- Version increase for new patch release
=> custom exceptions

pypyr/cli.py, pypyr/errors.py, pypyr/moduleloader.py, pypyr/pipelinerunner.py, pypyr/version.py, setup.cfg, tests/arbpack/arbmod.py, tests/arbpack/arbstep.py, tests/pipelines/smoke.yaml, tests/pipelines/testpipeline.yaml, tests/testfiles/arb.py, tests/unit/pypyr/errors_test.py, tests/unit/pypyr/moduleloader_test.py, tests/unit/pypyr/pipelinerunner_test.py
- PipelineNotFoundError and PyModuleNotFoundError added
- Red colour on exception bug - reset to normal terminal colour after error print done so subsequent cmds not also in red
- unit tests
=> Custom Errors and Unit tests

tests/unit/pypyr/context_test.py, tests/unit/pypyr/pipelinerunner_test.py
=> Minor unit test corrections

README.rst, pypyr/steps/fetchjson.py, pypyr/steps/fetchyaml.py, pypyr/version.py, setup.cfg, tests/unit/pypyr/steps/fetchjson_test.py, tests/unit/pypyr/steps/fetchyaml_test.py
- New fetchjson step
- New fetchyaml step
- README updates
- Version bump
=> Add fetchjson and fetchyaml steps

README.rst
- table with links to repos for official pypyr plug-ins
- fix duplicate header
=> Add plug-ins to README

README.rst, pypyr/steps/fetchjson.py, pypyr/steps/fetchyaml.py, pypyr/steps/fileformat.py, pypyr/steps/fileformatjson.py, pypyr/steps/fileformatyaml.py, pypyr/steps/filereplace.py, tests/unit/pypyr/context_test.py, tests/unit/pypyr/steps/fetchjson_test.py, tests/unit/pypyr/steps/fetchyaml_test.py, tests/unit/pypyr/steps/fileformat_test.py, tests/unit/pypyr/steps/fileformatjson_test.py, tests/unit/pypyr/steps/fileformatyaml_test.py, tests/unit/pypyr/steps/filereplace_test.py
- add string substitution support to 
- fetchjson
- fetchyaml
- fileformat
- fileformatjson
- fileformatyaml
- filereplace
=> file paths support string substitutions

README.rst, pypyr/context.py, pypyr/steps/fetchjson.py, pypyr/steps/fetchyaml.py, pypyr/steps/fileformat.py, pypyr/steps/fileformatjson.py, pypyr/steps/fileformatyaml.py, pypyr/steps/filereplace.py, pypyr/version.py, setup.cfg, tests/unit/pypyr/context_test.py, tests/unit/pypyr/steps/fetchjson_test.py, tests/unit/pypyr/steps/fetchyaml_test.py, tests/unit/pypyr/steps/fileformat_test.py, tests/unit/pypyr/steps/fileformatjson_test.py, tests/unit/pypyr/steps/fileformatyaml_test.py, tests/unit/pypyr/steps/filereplace_test.py
- [sic] strings, for when you don't want to apply {formatting} to a string
- README help updates for substitutions
- version bump
=> sic strings

pypyr/utils/poll.py, pypyr/version.py, setup.cfg, tests/unit/pypyr/utils/poll_test.py
- wait_until_true had an unnecessary wait after the last loop attempt finished executing. Remedied.
- version bump
=> wait_until_true remove redundant last wait

pypyr/utils/__init__.py, pypyr/version.py, setup.cfg
- utils folder missing __init__.py. Added.
=> make utils module available from pypi installs

README.rst, pypyr/context.py, pypyr/pipelinerunner.py, pypyr/steps/pype.py, pypyr/version.py, setup.cfg, tests/unit/pypyr/pipelinerunner_test.py, tests/unit/pypyr/steps/pype_test.py
- pypyr.steps.pype - run nested pipelines, run another pipeline from a pipeline step
- includes refactor of the pypyr core to accept already existing context
- the pypyr `Context` has a new `working_dir` attribute
- update api docstring documentation for pipelinerunner.py
- README updates for the new functionality
- version bump
=> pypyr.steps.pype

pypyr/version.py, setup.cfg, shippable.yaml
- Deploy error from cached build dir caused an error in previous release distributable.
=> no functional change>bump patch version 

README.rst, ops/shippable-pypi-release.sh, pypyr/context.py, pypyr/steps/contextmerge.py, pypyr/utils/types.py, pypyr/version.py, setup.cfg, tests/unit/pypyr/context_test.py, tests/unit/pypyr/steps/contextmerge_test.py, tests/unit/pypyr/utils/types_test.py
- contextmerge resolve #47 
- add type checker utils
=> contextmerge

README.rst, ops/shippable-pypi-release.sh, pypyr/parser/commas.py, pypyr/parser/list.py, pypyr/version.py, requirements.txt, setup.cfg, tests/unit/pypyr/parser/list_test.py
- pypyr.parser.list #54
- README double PRE tags
- #59 . fix version number on pypi deploy to dodge caching issue
=> pypyr.parser.list

README.rst
- README comments and links to docker repo.
=> docker README

CONTRIBUTING.rst, README.rst
- CONTRIBUTING guide
- discord link
=> contributing guide. discord link.

README.rst, pypyr/dsl.py, pypyr/errors.py, pypyr/utils/poll.py, pypyr/version.py, setup.cfg, setup.py, tests/unit/pypyr/dsl_test.py, tests/unit/pypyr/errors_test.py, tests/unit/pypyr/utils/poll_test.py
- while loop decorator
- README help with examples for all decorators
- burying the lead: major version bump for v1.0 release woohoo :fireworks: !
=> v1.0 & decorator: while

pypyr/cli.py, pypyr/log/logger.py, pypyr/pipelinerunner.py, tests/unit/pypyr/cli_test.py, tests/unit/pypyr/log/logger_test.py, tests/unit/pypyr/pipelinerunner_test.py
with this pypyr can log to file in addition to logging to stdout
=> log file handler

README.rst
=> fix envUnset example in README

README.rst, pypyr/context.py, pypyr/steps/fetchjson.py, pypyr/steps/fetchyaml.py, pypyr/steps/filewriteyaml.py, tests/unit/pypyr/context_test.py, tests/unit/pypyr/steps/fetchjson_test.py, tests/unit/pypyr/steps/fetchyaml_test.py, tests/unit/pypyr/steps/filewriteyaml_test.py
- fetchyaml into key
- fetchjson into key
- fiilewriteyaml step
=> fetch into key and filewriteyaml

README.rst, pypyr/steps/filewritejson.py, tests/unit/pypyr/steps/filewritejson_test.py
- filewritejson step
- README examples
=> filewritejson #86

pypyr/version.py, setup.cfg
- globbing
- pyypr.steps.debug
- contextsetf formatting
- pypyr.parser.dict
- new style dict input for all steps with >1 input context
- Affected steps are: assert, env, fileformat, fileformatjson, fileformatyaml, filereplace, tar
- shell/safeshell. save out to context option. Rename safeshell cmd. 
- built-in context parsers optional args
=> Bump version: 2.0.0 → 2.1.0

pypyr/errors.py, pypyr/moduleloader.py, pypyr/pipelinerunner.py, pypyr/pypeloaders/fileloader.py, pypyr/steps/pype.py, tests/arbpack/arbloader.py, tests/unit/pypyr/moduleloader_test.py, tests/unit/pypyr/pipelinerunner_test.py, tests/unit/pypyr/pypeloaders/fileloader_test.py, tests/unit/pypyr/steps/pype_test.py
=> Refactor the current get_pipeline_definition to a new loader class

README.rst
- no functional change, just add some example links to README
=> fetchjson and fetchyaml doc example link #118

README.rst
Fix README doc to use correct contextSetf
=> contextSetf doc fix

README.rst, pypyr/steps/pype.py, pypyr/version.py, setup.cfg, tests/unit/pypyr/steps/pype_test.py
* add string interpolation to pypyr.steps.pype input.
* bump minor version for release
=> add substitutions to pype step, closes #76

pypyr/context.py, tests/unit/pypyr/context_test.py
=> Resolve SpecialTag directives at context merge

README.rst
=> glob, closes #145

pypyr/steps/glob.py, pypyr/version.py, setup.cfg, tests/unit/pypyr/steps/glob_test.py
- glob step (previous merge was just README)
-  bump version
=> Glob + bump version 2.9.0

pypyr/dsl.py, pypyr/yaml.py, tests/common/utils.py, tests/unit/pypyr/dsl_test.py, tests/unit/pypyr/stepsrunner_test.py
=> Save step errors to the context on failure

README.rst, pypyr/version.py, setup.cfg
Readme updates for onError and runErrors
version bump
=> readme for onerror and runerrors #139

conftest.py, pypyr/dsl.py, pypyr/log/logger.py, pypyr/steps/echo.py, tests/unit/pypyr/dsl_test.py, tests/unit/pypyr/log/logger_test.py, tests/unit/pypyr/steps/echo_test.py
=> Add new logging level notice

README.rst, pypyr/cli.py, pypyr/log/logger.py, pypyr/version.py, setup.cfg, tests/unit/pypyr/cli_test.py
- new notify level default for cli
- version bump for release
=> Clidefault25

pypyr/steps/pypyrversion.py, tests/unit/pypyr/steps/pypyrversion_test.py
=> NOTIFY output for pypyrversion. ref #132

setup.py
* trove classifier missing comma
=> fix trove classifier on pypi for topic: utilities

pypyr/steps/debug.py, tests/unit/pypyr/steps/debug_test.py
=> Debug-step use pformat instead of json

pypyr/version.py, setup.cfg
bump version to 3.0.1
to release  
* #149 
* #163 (Context: merge - apply interpolation on different types #163)
=> Bump version: 3.0.0 → 3.0.1

conftest.py, pypyr/cli.py, pypyr/log/logger.py, pypyr/pipelinerunner.py, pypyr/version.py, setup.cfg, tests/integration/pypyr/pipelinerunner_int_test.py, tests/unit/pypyr/cli_test.py, tests/unit/pypyr/log/logger_test.py, tests/unit/pypyr/pipelinerunner_test.py
- API change: move logging config and logging handler setup from pipelinerunner to the cli. Closes #173, #172. 
- version bump
=> Logging config/setup to cli application from library

tests/integration/pypyr/utils/filesystem_int_test.py, tests/unit/pypyr/dsl_test.py, tests/unit/pypyr/stepsrunner_test.py
new version of flake8 introduced some new lint rules. minor/non-functional changes to pass new flake8 checks.
=> fix style rules for new flake8 version

ops/tag.yaml, pypyr/steps/dsl/cmd.py, tests/unit/pypyr/steps/cmd_step_test.py
- rstrip cmdOut output
- unit tests for the same
=> remove /r/n from cmd/shell out

README.md
=> remove discord from readme.

pypyr/retries.py, setup.cfg, setup.py, tests/unit/pypyr/formatting_test.py, tests/unit/pypyr/retries_test.py, tests/unit/pypyr/steps/cmd_step_test.py, tests/unit/pypyr/steps/pype_test.py
Fix #223 and #223 to allow ops/build success:
- fix linting issues (W503 ignore, W504 adopted and code fixed)
- include fix to #224 (otherwise the ops/build fails)
=> Fix failing ops/build (failing on linting issues and locale dependent failure)

pypyr/dsl.py, tests/unit/pypyr/dsl_test.py
=> Evaluate step skip only if the run check returned true

pypyr/config.py, pypyr/platform.py, pypyr/toml.py
Minor typings improvements for config, platform and tomli-w.
=> typings for config, platform

pypyr/parser/list.py, pypyr/parser/string.py
No functional change. Minor improvement.
closes #291
=> remove redundant dict on parser context init

pypyr/steps/dsl/cof.py
- minor typing on return type for dsl.cof functions
=> typing on dsl.cof

.github/workflows/lint-test-build.yaml, .github/workflows/publish.yaml, ops/build.yaml, pyproject.toml
Retire previous codecov pip package uploader.
Migrate to new github action.
=> new codecov uploader

pypyr/__init__.py, setup.cfg
- No new features
- Includes:
- Validate python 3.11 compatibility (py 3.11 added to CI build/test matrix)
- Bug fix for `pypyr.steps.filereplace`
- codecov upgrade to new uploader
=> Bump version: 5.7.0 → 5.7.1

tests/unit/pypyr/steps/dsl/venv_dsl_test.py
venv integration tests were assuming ordered results, but the async execution in parallel might mean that the post-install steps start in any given order, it's not guaranteed.
Fix is to amend tests to enforce the results expected based on the path input in the mocked object.
=> fix venv flaky test
